In [92]:
## Check that text files are accurately converted to npzs
import pandas as pd
file_path = '../data/tempdata/L_002.xlsx'
df = pd.read_excel(file_path, header = None)#, delimiter=' ', lineterminator='\n', header=None)  # Adjust the delimiter if needed (e.g., ',' for CSV)

df.head()
# df.shape

FileNotFoundError: [Errno 2] No such file or directory: '../data/tempdata/v7_lat.xlsx'

In [141]:
# import numpy as np
import pandas as pd
# df_npz = pd.DataFrame(np.load('../data/840/v8_lred_002.npz')['arr_0'])
#lat, lon (0,0) occurs at lat row 360 and lon row 0
# np.load('../data/840/v8_lred_002.npz')['arr_0'][360][0]
df_npz = pd.DataFrame(np.load('../data/840/v7_lon.npz')['arr_0'])
# df_npz
# df_npz.shape
# df_npz.head()

np.mod(np.load('../data/840/v7_lon.npz')['arr_0'], 360)
# rows_with_zeros = df_npz[(df_npz == 0).any(axis=1)]
# 0.947 + (1.195-0.947)/2
# print(rows_with_zeros)

array([[  0.   ,   1.125,   2.25 , ..., 357.75 , 358.875,   0.   ],
       [  0.   ,   1.125,   2.25 , ..., 357.75 , 358.875,   0.   ],
       [  0.   ,   1.125,   2.25 , ..., 357.75 , 358.875,   0.   ],
       ...,
       [  0.   ,   1.125,   2.25 , ..., 357.75 , 358.875,   0.   ],
       [  0.   ,   1.125,   2.25 , ..., 357.75 , 358.875,   0.   ],
       [  0.   ,   1.125,   2.25 , ..., 357.75 , 358.875,   0.   ]])

In [143]:
import numpy as np
import pandas as pd


#create a fake lat or lon.
# Calculate the number of rows
num_rows = int(180 / 0.25) + 1  # 180 because 90 - (-90) = 180

# Initialize the ndarray with zeros

ndarray = np.zeros((num_rows, 1441))
    # Fill the ndarray
islat = True
for i in range(num_rows):
    if islat:
        #inconsistent across ITU Rs.  sometimes sorted asc, descending
        # ndarray[i] = -90 + i * 0.25
        ndarray[i] = 90 - i * 0.25
        df_npz = pd.DataFrame(np.load('../data/840/v8_lat.npz')['arr_0'])
    else:
        ndarray[i] = np.linspace(0,360,1441)
        df_npz = pd.DataFrame(np.load('../data/840/v8_lon.npz')['arr_0'])


print("Shape of the ndarray:", ndarray.shape)
np.savez('../data/840/v8_lon.npz',ndarray)
np.load('../data/840/v8_lon.npz')['arr_0']

# #compare the dataframes
# df = pd.DataFrame(np.load('../data/840/v8_lon_fake.npz')['arr_0'])
# df.shape
# df.head()
# print(df.compare(df_npz))

Shape of the ndarray: (721, 1441)


array([[ 90.  ,  90.  ,  90.  , ...,  90.  ,  90.  ,  90.  ],
       [ 89.75,  89.75,  89.75, ...,  89.75,  89.75,  89.75],
       [ 89.5 ,  89.5 ,  89.5 , ...,  89.5 ,  89.5 ,  89.5 ],
       ...,
       [-89.5 , -89.5 , -89.5 , ..., -89.5 , -89.5 , -89.5 ],
       [-89.75, -89.75, -89.75, ..., -89.75, -89.75, -89.75],
       [-90.  , -90.  , -90.  , ..., -90.  , -90.  , -90.  ]])

In [140]:
df = pd.DataFrame(np.load('../data/840/v7_lred_02.npz')['arr_0'])

# Value to find
value_to_find = 3.701652

# Finding row and column indices
indices = [(row, col) for row, col in zip(*((df == value_to_find).values).nonzero())]

print("Row and column indices of value", value_to_find, "are:", indices)

Row and column indices of value 3.701652 are: []


In [22]:
import numpy as np

#create a fake lat or lon.
stepsize = 0.25
# Calculate the number of rows
num_rows = int(180 / stepsize) + 1  # 180 because 90 - (-90) = 180

# Initialize the ndarray with zeros

ndarray = np.zeros((num_rows, 1441))
    # Fill the ndarray
islat = False
for i in range(num_rows):
    if islat:
        ndarray[i] = 0 + i * stepsize
    else:
        ndarray[i] = np.linspace(0,360,1441)


print("Shape of the ndarray:", ndarray.shape)
np.savez('../data/840/v8_lon.npz',ndarray)
np.load('../data/840/v8_lon.npz')['arr_0']

#compare the dataframes
# df = pd.DataFrame(np.load('../data/840/v8_lon_fake.npz')['arr_0'])
# df.shape
# df.head()
# print(df.compare(df_npz))

Shape of the ndarray: (721, 1441)


array([[0.0000e+00, 2.5000e-01, 5.0000e-01, ..., 3.5950e+02, 3.5975e+02,
        3.6000e+02],
       [0.0000e+00, 2.5000e-01, 5.0000e-01, ..., 3.5950e+02, 3.5975e+02,
        3.6000e+02],
       [0.0000e+00, 2.5000e-01, 5.0000e-01, ..., 3.5950e+02, 3.5975e+02,
        3.6000e+02],
       ...,
       [0.0000e+00, 2.5000e-01, 5.0000e-01, ..., 3.5950e+02, 3.5975e+02,
        3.6000e+02],
       [0.0000e+00, 2.5000e-01, 5.0000e-01, ..., 3.5950e+02, 3.5975e+02,
        3.6000e+02],
       [0.0000e+00, 2.5000e-01, 5.0000e-01, ..., 3.5950e+02, 3.5975e+02,
        3.6000e+02]])

In [24]:
np.load('../data/840/v8_lat.npz')['arr_0']


array([[ 90.  ,  90.  ,  90.  , ...,  90.  ,  90.  ,  90.  ],
       [ 89.75,  89.75,  89.75, ...,  89.75,  89.75,  89.75],
       [ 89.5 ,  89.5 ,  89.5 , ...,  89.5 ,  89.5 ,  89.5 ],
       ...,
       [-89.5 , -89.5 , -89.5 , ..., -89.5 , -89.5 , -89.5 ],
       [-89.75, -89.75, -89.75, ..., -89.75, -89.75, -89.75],
       [-90.  , -90.  , -90.  , ..., -90.  , -90.  , -90.  ]])

In [17]:
import numpy as np

stepsize = 0.25
# Calculate the number of rows
num_rows = int(180 / stepsize) + 1  # 180 because 90 - (-90) = 180

# Initialize the ndarray with zeros
ndarray = np.zeros((num_rows, 321))

# Fill the ndarray
for i in range(num_rows):
    ndarray[i] = 90 - i * stepsize

print("Shape of the ndarray:", ndarray.shape)
np.savez('../data/840/v8_lon.npz',ndarray)
np.load('../data/840/v8_lon.npz')['arr_0']

Shape of the ndarray: (721, 321)


array([[ 90.  ,  90.  ,  90.  , ...,  90.  ,  90.  ,  90.  ],
       [ 89.75,  89.75,  89.75, ...,  89.75,  89.75,  89.75],
       [ 89.5 ,  89.5 ,  89.5 , ...,  89.5 ,  89.5 ,  89.5 ],
       ...,
       [-89.5 , -89.5 , -89.5 , ..., -89.5 , -89.5 , -89.5 ],
       [-89.75, -89.75, -89.75, ..., -89.75, -89.75, -89.75],
       [-90.  , -90.  , -90.  , ..., -90.  , -90.  , -90.  ]])

In [4]:
# mypath = "C:\\Users\\rayma\\Downloads\\ITUR 840-9\\R-REC-P.840Part1-0-202308-I!!ZIP-E\\"
mypath = "../data/tempdata/"
from os import listdir
from os.path import isfile, join
onlyfiles = [f for f in listdir(mypath) if isfile(join(mypath, f))]
print(onlyfiles)
# fname = 'PL.txt'
# available_p = np.array(
#         [0.1, 0.2, 0.3, 0.5, 1.0, 2.0, 3.0, 5.0, 10.0, 20.0, 30.0, 50.0,
#          60.0, 70.0, 80.0, 90.0, 95.0, 99.0])
# for p in available_p:
#     fname = 'L_'
# df = display_txt_file_info(logNfilepath+fname)
# np.savez('../data/840/v8_pclw.npz', df_9.astype(float).to_numpy())

['L_001.TXT', 'L_002.TXT', 'L_003.TXT', 'L_005.TXT', 'L_01.TXT', 'L_02.TXT', 'L_03.TXT', 'L_05.TXT', 'L_1.TXT', 'L_10.TXT', 'L_100.TXT', 'L_2.TXT', 'L_20.TXT', 'L_3.TXT', 'L_30.TXT', 'L_5.TXT', 'L_50.TXT', 'L_60.TXT', 'L_70.TXT', 'L_80.TXT', 'L_90.TXT', 'L_95.TXT', 'L_99.TXT', 'L_mean.TXT', 'L_std.TXT', 'v8_lred_001.npz', 'v8_lred_002.npz', 'v8_lred_003.npz', 'v8_lred_005.npz', 'v8_lred_01.npz', 'v8_lred_02.npz', 'v8_lred_03.npz', 'v8_lred_05.npz', 'v8_lred_1.npz', 'v8_lred_10.npz', 'v8_lred_100.npz', 'v8_lred_2.npz', 'v8_lred_20.npz', 'v8_lred_3.npz', 'v8_lred_30.npz', 'v8_lred_5.npz', 'v8_lred_50.npz', 'v8_lred_60.npz', 'v8_lred_70.npz', 'v8_lred_80.npz', 'v8_lred_90.npz', 'v8_lred_95.npz', 'v8_lred_99.npz']


In [ ]:
# pd.read_csv(mypath + "/" + 'L_001.xlsx', delimiter=' ', lineterminator='\n', header=None)

In [7]:
##create the npz files used to calculate just about everything in 840.
import re
import numpy as np
import pandas as pd

def transform_filename(filename):
    # Use regular expressions to extract the numerical part of the filename
    match = re.search(r'_(\d+)\.TXT', filename)
    if match:
        num = match.group(1)
        new_filename = f'v8_lred_{num}.npz'
        return new_filename
    else:
        return None

# Example usage
new_filename = []
count = 0
for i in onlyfiles:
    print(onlyfiles[count])
    df = pd.read_csv(mypath + onlyfiles[count], delimiter=' ', lineterminator='\n', header=None)
    reversed_df = df.iloc[::-1].reset_index(drop=True)
    # df = display_txt_file_info(mypath + "\\" + onlyfiles[count])
    # print(df.head())
    # if it were a numpy array then do this: reversed_array = array[::-1]
    newname = transform_filename("/data/840/" + onlyfiles[count])
    # print(newname)
    np.savez(newname, reversed_df.astype(float).to_numpy())
    
    count+=1
    
## THEY ARE ALL PERFECTLY SHAPED!!!

L_001.TXT
L_002.TXT
L_003.TXT
L_005.TXT
L_01.TXT
L_02.TXT
L_03.TXT
L_05.TXT
L_1.TXT
L_10.TXT
L_100.TXT
L_2.TXT
L_20.TXT
L_3.TXT
L_30.TXT
L_5.TXT
L_50.TXT
L_60.TXT
L_70.TXT
L_80.TXT
L_90.TXT
L_95.TXT
L_99.TXT
L_mean.TXT


TypeError: expected str, bytes or os.PathLike object, not NoneType

In [104]:
# check data in npz
from os import listdir
from os.path import isfile, join
mypath = '../data/840/'
onlyfiles = [f for f in listdir(mypath) if isfile(join(mypath, f))]
new_filename = []
count = 0
for i in onlyfiles:
    print(i, ' ', np.load(mypath+i)['arr_0'].shape)
    # print(onlyfiles[count])

    
    count+=1

v4_esawred_01.npz   (161, 321)
v4_esawred_02.npz   (161, 321)
v4_esawred_03.npz   (161, 321)
v4_esawred_05.npz   (161, 321)
v4_esawred_1.npz   (161, 321)
v4_esawred_10.npz   (161, 321)
v4_esawred_2.npz   (161, 321)
v4_esawred_20.npz   (161, 321)
v4_esawred_3.npz   (161, 321)
v4_esawred_30.npz   (161, 321)
v4_esawred_5.npz   (161, 321)
v4_esawred_50.npz   (161, 321)
v4_esawred_60.npz   (161, 321)
v4_esawred_70.npz   (161, 321)
v4_esawred_80.npz   (161, 321)
v4_esawred_90.npz   (161, 321)
v4_esawred_95.npz   (161, 321)
v4_esawred_99.npz   (161, 321)
v4_lat.npz   (161, 321)
v4_lon.npz   (161, 321)
v4_wred_lognormal_mean.npz   (161, 321)
v4_wred_lognormal_pclw.npz   (161, 321)
v4_wred_lognormal_stdev.npz   (161, 321)
v6_lat.npz   (161, 321)
v6_lon.npz   (161, 321)
v6_lred_01.npz   (161, 321)
v6_lred_02.npz   (161, 321)
v6_lred_03.npz   (161, 321)
v6_lred_05.npz   (161, 321)
v6_lred_1.npz   (161, 321)
v6_lred_10.npz   (161, 321)
v6_lred_2.npz   (161, 321)
v6_lred_20.npz   (161, 321)
v6_lred

In [86]:
from itur.models.itu1144 import bilinear_2D_interpolator
from itur.utils import (dataset_dir, prepare_input_array, prepare_output_array,
                        prepare_quantity, load_data_interpolator,
                        get_input_type)

lred = load_data_interpolator(
    '../data/840/v8_lat.npz',
    '../data/840/v8_lon.npz',
    '../data/840/v8_lred_5.npz',
    bilinear_2D_interpolator,
    flip_ud=False
)
print(lred.values)

# print(np.load('../data/840/v7_lat.npz')['arr_0'].shape)
# print(np.load('../data/840/v7_lon.npz')['arr_0'])
# print(np.load('../data/840/v7_lred_95.npz')['arr_0'])

print(np.load('../data/840/v8_lat.npz')['arr_0'].shape)
# print(np.load('../data/840/v8_lon.npz')['arr_0'])
# print(np.load('../data/840/v8_lred_95.npz')['arr_0'])


[[0.122 0.122 0.122 ... 0.122 0.122 0.122]
 [0.123 0.123 0.123 ... 0.123 0.123 0.123]
 [0.123 0.123 0.123 ... 0.123 0.123 0.123]
 ...
 [0.    0.    0.    ... 0.    0.    0.   ]
 [0.    0.    0.    ... 0.    0.    0.   ]
 [0.    0.    0.    ... 0.    0.    0.   ]]
(721, 1441)


In [69]:
import numpy as np

# Calculate the number of rows
num_rows = int(180 / 0.25) + 1  # 180 because 90 - (-90) = 180

# Initialize the ndarray with zeros
ndarray = np.zeros((num_rows, 1441))

# Fill the ndarray
for i in range(num_rows):
    ndarray[i] = 90 - i * 0.25

print("Shape of the ndarray:", ndarray.shape)
print(ndarray)

Shape of the ndarray: (721, 1441)
[[ 90.    90.    90.   ...  90.    90.    90.  ]
 [ 89.75  89.75  89.75 ...  89.75  89.75  89.75]
 [ 89.5   89.5   89.5  ...  89.5   89.5   89.5 ]
 ...
 [-89.5  -89.5  -89.5  ... -89.5  -89.5  -89.5 ]
 [-89.75 -89.75 -89.75 ... -89.75 -89.75 -89.75]
 [-90.   -90.   -90.   ... -90.   -90.   -90.  ]]


In [93]:
# lats_o[2:-2, 2:-2]
# lats_o = np.load('../data/840/v8_lat.npz')['arr_0'][2:-2, 2:-2]
# lons_o = np.load('../data/840/v8_lon.npz')['arr_0'][2:-2, 2:-2]
print(np.atleast_2d(np.load('../data/840/v8_lat.npz')['arr_0']).shape)
print(np.atleast_2d(np.load('../data/840/v8_lon.npz')['arr_0']).shape)
print(np.atleast_2d(np.load('../data/840/v8_lred_5.npz')['arr_0']).shape)
# print(lats_o)
# print(lons_o)

# from itur.models.itu1144 import is_regular_grid
# is_regular_grid(lats_o[2:-2, 2:-2], lons_o[2:-2, 2:-2])

(721, 1441)
(721, 1441)
(721, 1441)


In [16]:
np.load('../data/840/v8_lat.npz')['arr_0']

array([[ 90.  ,  90.  ,  90.  , ...,  90.  ,  90.  ,  90.  ],
       [ 89.75,  89.75,  89.75, ...,  89.75,  89.75,  89.75],
       [ 89.5 ,  89.5 ,  89.5 , ...,  89.5 ,  89.5 ,  89.5 ],
       ...,
       [-89.5 , -89.5 , -89.5 , ..., -89.5 , -89.5 , -89.5 ],
       [-89.75, -89.75, -89.75, ..., -89.75, -89.75, -89.75],
       [-90.  , -90.  , -90.  , ..., -90.  , -90.  , -90.  ]])

In [8]:
# import xlrd
# path_to_my_workbook = '../test/test_data/840/cloud_liquid_9.xlsx'
# wb = xlrd.open_workbook(path_to_my_workbook)
# ws = wb.sheet_by_index(0)
# mylist = ws.col_values(0)
# print(mylist)

import pandas
path_to_my_workbook = './test/test_data/840/cloud_liquid_9.xlsx'

df = pandas.read_excel(path_to_my_workbook) # The options of that method are quite neat; Stores to a pandas.DataFrame object
print ( df.head() )# show a preview of the loaded data
idx_of_column = 5-1 # in case the column of interest is the 5th in Excel
print( list(df.iloc[:,idx_of_column]) )# access via index
print( list(df.loc[['my_row_1','my_row_2'],['my_column_1','my_column_2']]) )# access certain elements via row and column names
print( list(df['my_column_1']) )# straight forward access via column name

FileNotFoundError: [Errno 2] No such file or directory: './test/test_data/840/cloud_liquid_9.xlsx'

In [91]:
my_df = pd.DataFrame(np.load('v7_lat.npz')['arr_0'])
# my_df.to_csv('list.csv', index=False)



FileNotFoundError: [Errno 2] No such file or directory: 'v7_lat.npz'

In [145]:
import itur
import itur.models
import itur.models.itu840

# Define input attributes
lat = 0.0  #  (°N)
lon = 0.0  # (°E)
# f = 6  # (GHz)
# el = 31.07699124  # (°)
p = 1.0 # (%)

# Make call to test-function cloud_attenuation
itur_val = itur.models.itu840.columnar_content_reduced_liquid(lat, lon, p)
print(itur_val)
# Compute error with respect to value in ITU example file
# ITU_example_val = 0.45516982  # (dB)
# error = ITU_example_val - itur_val.value
# error_rel = error / ITU_example_val * 100  # (%)

lat used: [[0.]], lon used: [[0.]]
P is 1.0, P_below is 1.0, P_above is 1.0
3.0248978 kg / m2
